import Link from "next/link"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "amanda practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
		<div className="bg-white p-10">
			<Link href="/" className="mr-10 text-black">home</Link>
			<Link href="/list" className="mr-10 text-black">List</Link>
		</div>
		{children}
	</body>
    </html>
  );
}
